### ISSUE TITLE
Incorrect / Weird example sentence for "fortsetzen"

### ISSUE THREAD

**Issue by tneumueller** [ThomasWicksWeb/GermanWordADay#2]
Wanted to submit this on your website in the contact form, but submitting it gives me an error.

I noticed a mistake on "germanwordaday". Today's word is "fortsetzen - to continue" and the example sentence is "Verb - Willst du fortsetzen im Spiel?". As a native speaker this sounds strange to me (pretty sure its incorrect), I would rather say "Willst du das Spiel fortsetzen?", that sounds more natural.

**Comment by ThomasWicksWeb** [comment]
Hey tneumueller,

Thanks for pointing this out for me. I just corrected it.
